# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Mana Burnout"

domain: manaburnout.tech

# A description of your site for meta tag, search engine results.
description: "Thoughts on tech, work, and staying human"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://manaburnout.tech/"

# Favicon
favicon: images/favicon.png

# Logo
logo: images/logo.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Tags
    url: /tags

# Colors
accent_color: '#2727e0'

# Site footer
footer:
  content: "&copy; Mana Burnout all rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown:    kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

# Sass
sass:
  sass_dir: _sass
  style: compressed
